Artist.destroy_all
Album.destroy_all
Song.destroy_all


belakor = Artist.create!(name: "Be'lakor", genre: "Melodic Death Metal", country: "Australia", website: "belakorband.com", remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/belakor_ogbgsg.jpg")
burial = Artist.create!(name: "Burial", genre: "Dubstep", country: "Great Britain", website: "burial.bandcamp.com", remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/burial_qf8qnk.jpg")
insomnium = Artist.create!(name: "Insomnium", genre: "Melodic Death Metal", country: "Finland", website: "insomnium.net", remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/insomnium_lt3gzo.jpg")
katatonia = Artist.create!(name: "Katatonia", genre: "Progressive Metal", country: "Sweden", website: "katatonia.com", remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710095/katatonia_vbwedk.jpg")
rammstein = Artist.create!(name: "Rammstein", genre: "Neue Deutsche Harde", country: "Germany", website: "rammstein.de", remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/rammstein_s1r2j2.jpg")

belakor_of_breath_and_bone= Album.create!(name: "Of Breath and Bone", year: 2012, artist: belakor, remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/belakor_of_breath_and_bone_rgoder.jpg")
insomnium_winters_gate= Album.create!(name: "Winter's Gate", year: 2016, artist: insomnium, remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/insomnium_winters_gate_xqubow.jpg")
insomnium_above_the_weeping_world = Album.create!(name: "Above the Weeping World", year: 2006, artist: insomnium, remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/insomnium_above_the_weeping_world_mm3xnj.jpg")
burial_untrue = Album.create!(name: "Untrue", year: 2007, artist: burial, remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/burial_untrue_lpgelf.jpg")
katatonia_the_fall_of_hearts = Album.create!(name: "The Fall of Hearts", year: 2016, artist: katatonia, remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/katatonia_fall_of_hearts_pnqiec.jpg")
rammstein_reise_reise = Album.create!(name: "Reise, Reise", artist: rammstein, year: 2004, remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/rammstein_reise_reise_f49uww.jpg")

Song.create!( name: "Part 1", album: insomnium_winters_gate, track_number: 1 )
Song.create!( name: "Part 2", album: insomnium_winters_gate, track_number: 2 )
Song.create!( name: "Part 3", album: insomnium_winters_gate, track_number: 3 )
Song.create!( name: "Part 4", album: insomnium_winters_gate, track_number: 4 )
Song.create!( name: "Part 5", album: insomnium_winters_gate, track_number: 5 )
Song.create!( name: "Part 6", album: insomnium_winters_gate, track_number: 6 )
Song.create!( name: "Part 7", album: insomnium_winters_gate, track_number: 6 )
Song.create!( name: "Abeyance", album: belakor_of_breath_and_bone, track_number: 1 )
Song.create!( name: "Remnants", album: belakor_of_breath_and_bone, track_number: 2 )
Song.create!( name: "Fraught", album: belakor_of_breath_and_bone, track_number: 3 )
Song.create!( name: "Absit Omen", album: belakor_of_breath_and_bone, track_number: 4 )
Song.create!( name: "To Stir the Sea", album: belakor_of_breath_and_bone, track_number: 5 )
Song.create!( name: "In Parting", album: belakor_of_breath_and_bone, track_number: 6 )
Song.create!( name: "The Dream and the Waking", album: belakor_of_breath_and_bone, track_number: 7 )
Song.create!( name: "By Moon and Star", album: belakor_of_breath_and_bone, track_number: 8 )
Song.create!( name: "The Gale", album: insomnium_above_the_weeping_world, track_number: 1 )
Song.create!( name: "Mortal Share", album: insomnium_above_the_weeping_world, track_number: 2 )
Song.create!( name: "Drawn to Black", album: insomnium_above_the_weeping_world, track_number: 3 )
Song.create!( name: "Change of Heart", album: insomnium_above_the_weeping_world, track_number: 4 )
Song.create!( name: "At the Gates of Sleep", album: insomnium_above_the_weeping_world, track_number: 5 )
Song.create!( name: "The Killjoy", album: insomnium_above_the_weeping_world, track_number: 6 )
Song.create!( name: "Last Statement", album: insomnium_above_the_weeping_world, track_number: 7 )
Song.create!( name: "Devoid of Caring", album: insomnium_above_the_weeping_world, track_number: 8 )
Song.create!( name: "In the Groves of Death", album: insomnium_above_the_weeping_world, track_number: 9 )
Song.create!( name: "Takeover", album: katatonia_the_fall_of_hearts, track_number: 1 )
Song.create!( name: "Serein", album: katatonia_the_fall_of_hearts, track_number: 2 )
Song.create!( name: "Old Heart Falls", album: katatonia_the_fall_of_hearts, track_number: 3 )
Song.create!( name: "Decima", album: katatonia_the_fall_of_hearts, track_number: 4 )
Song.create!( name: "Sanction", album: katatonia_the_fall_of_hearts, track_number: 5 )
Song.create!( name: "Residual", album: katatonia_the_fall_of_hearts, track_number: 6 )
Song.create!( name: "Serac", album: katatonia_the_fall_of_hearts, track_number: 7 )
Song.create!( name: "Last Song Before the Fade", album: katatonia_the_fall_of_hearts, track_number: 8 )
Song.create!( name: "Shifts", album: katatonia_the_fall_of_hearts, track_number: 9 )
Song.create!( name: "The Night Subscriber", album: katatonia_the_fall_of_hearts, track_number: 10 )
Song.create!( name: "Pale Flag", album: katatonia_the_fall_of_hearts, track_number: 11 )
Song.create!( name: "Passer", album: katatonia_the_fall_of_hearts, track_number: 12 )
Song.create!( name: "Untitled", album: burial_untrue, track_number: 1 )
Song.create!( name: "Archangel", album: burial_untrue, track_number: 2 )
Song.create!( name: "Near Dark", album: burial_untrue, track_number: 3 )
Song.create!( name: "Ghost Hardware", album: burial_untrue, track_number: 4 )
Song.create!( name: "Endorphin", album: burial_untrue, track_number: 5 )
Song.create!( name: "Etched Headplate", album: burial_untrue, track_number: 6 )
Song.create!( name: "In McDonalds", album: burial_untrue, track_number: 7 )
Song.create!( name: "Untrue", album: burial_untrue, track_number: 8 )
Song.create!( name: "Shell of Light", album: burial_untrue, track_number: 9 )
Song.create!( name: "Dog Shelter", album: burial_untrue, track_number: 10 )
Song.create!( name: "Homeless", album: burial_untrue, track_number: 11 )
Song.create!( name: "UK", album: burial_untrue, track_number: 12)
Song.create!( name: "Raver", album: burial_untrue, track_number: 13 )
Song.create!( name: "Reise, Reise", album: rammstein_reise_reise, track_number: 1 )
Song.create!( name: "Mein Teil", album: rammstein_reise_reise, track_number: 2 )
Song.create!( name: "Dalai Lama", album: rammstein_reise_reise, track_number: 3 )
Song.create!( name: "Keine Lust", album: rammstein_reise_reise, track_number: 4 )
Song.create!( name: "Los", album: rammstein_reise_reise, track_number: 5 )
Song.create!( name: "Amerika", album: rammstein_reise_reise, track_number: 6 )
Song.create!( name: "Moskau", album: rammstein_reise_reise, track_number: 7 )
Song.create!( name: "Morgenstern", album: rammstein_reise_reise, track_number: 8 )
Song.create!( name: "Stein um Stein", album: rammstein_reise_reise, track_number: 9 )
Song.create!( name: "Ohne Dich", album: rammstein_reise_reise, track_number: 10 )
Song.create!( name: "Amour", album: rammstein_reise_reise, track_number: 11 )

user1 = User.create!(email:"henk@jan.com", password:"123456" )
