Artist.destroy_all


belakor = Artist.create!(name: "Be'lakor", genre: "Melodic Death Metal", country: "Australia", website: "belakorband.com")
insomnium = Artist.create!(name: "Insomnium", genre: "Melodic Death Metal", country: "Finland", website: "insomnium.net")
burial = Artist.create!(name: "Burial", genre: "Dubstep", country: "Great Britain", website: "burial.bandcamp.com")
katatonia = Artist.create!(name: "Katatonia", genre: "Progressive Metal", country: "Sweden", website: "katatonia.com")
rammstein = Artist.create!(name: "Rammstein", genre: "Neue Deutsche Harde", country: "Germany", website: "rammstein.de")

belakor_image = ArtistImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/belakor_ogbgsg.jpg", artist: belakor)
insomnium_image =  ArtistImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/insomnium_lt3gzo.jpg", artist: insomnium)
burial_image =  ArtistImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/burial_qf8qnk.jpg", artist: burial )
katatonia_image =  ArtistImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710095/katatonia_vbwedk.jpg", artist: katatonia )
rammstein_image =  ArtistImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710094/rammstein_s1r2j2.jpg", artist: rammstein)

belakor_of_breath_and_bone_image = AlbumImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/belakor_of_breath_and_bone_rgoder.jpg")
insomnium_winters_gate_image = AlbumImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/insomnium_winters_gate_xqubow.jpg")
insomnium_above_the_weeping_world_image = AlbumImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/insomnium_above_the_weeping_world_mm3xnj.jpg")
burial_untrue_image = AlbumImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/burial_untrue_lpgelf.jpg")
katatonia_the_fall_of_hearts_image = AlbumImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/katatonia_fall_of_hearts_pnqiec.jpg")
rammstein_reise_reise_image = AlbumImage.create!(remote_image_url: "http://res.cloudinary.com/dr9a28l84/image/upload/v1495710088/rammstein_reise_reise_f49uww.jpg")

Song.create!( name: "Part 1", album: "Winter’s Gate", track_number: " 1", year: "2016", artist: insomnium, album_image: insomnium_winters_gate_image)
Song.create!( name: "Part 2", album: "Winter’s Gate", track_number: " 2", year: "2016", artist: insomnium, album_image: insomnium_winters_gate_image)
Song.create!( name: "Part 3", album: "Winter’s Gate", track_number: " 3", year: "2016", artist: insomnium, album_image: insomnium_winters_gate_image)
Song.create!( name: "Part 4", album: "Winter’s Gate", track_number: " 4", year: "2016", artist: insomnium, album_image: insomnium_winters_gate_image)
Song.create!( name: "Part 5", album: "Winter’s Gate", track_number: " 5", year: "2016", artist: insomnium, album_image: insomnium_winters_gate_image)
Song.create!( name: "Part 6", album: "Winter’s Gate", track_number: " 6", year: "2016", artist: insomnium, album_image: insomnium_winters_gate_image)
Song.create!( name: "Part 7", album: "Winter’s Gate", track_number: " 6", year: "2016", artist: insomnium, album_image: insomnium_winters_gate_image)
Song.create!( name: "Abeyance", album: "Of Breath and Bone", track_number: " 1", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "Remnants", album: "Of Breath and Bone", track_number: " 2", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "Fraught", album: "Of Breath and Bone", track_number: " 3", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "Absit Omen", album: "Of Breath and Bone", track_number: " 4", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "To Stir the Sea", album: "Of Breath and Bone", track_number: " 5", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "In Parting", album: "Of Breath and Bone", track_number: " 6", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "The Dream and the Waking", album: "Of Breath and Bone", track_number: " 7", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "By Moon and Star", album: "Of Breath and Bone", track_number: " 8", year: "2012", artist: belakor, album_image: belakor_of_breath_and_bone_image)
Song.create!( name: "The Gale", album: "Above the Weeping World", track_number: " 1", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "Mortal Share", album: "Above the Weeping World", track_number: " 2", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "Drawn to Black", album: "Above the Weeping World", track_number: " 3", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "Change of Heart", album: "Above the Weeping World", track_number: " 4", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "At the Gates of Sleep", album: "Above the Weeping World", track_number: " 5", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "The Killjoy", album: "Above the Weeping World", track_number: " 6", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "Last Statement", album: "Above the Weeping World", track_number: " 7", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "Devoid of Caring", album: "Above the Weeping World", track_number: " 8", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "In the Groves of Death", album: "Above the Weeping World", track_number: " 9", year: "2006", artist: insomnium, album_image: insomnium_above_the_weeping_world_image)
Song.create!( name: "Takeover", album: "The Fall of Hearts", track_number: " 1", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Serein", album: "The Fall of Hearts", track_number: " 2", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Old Heart Falls", album: "The Fall of Hearts", track_number: " 3", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Decima", album: "The Fall of Hearts", track_number: " 4", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Sanction", album: "The Fall of Hearts", track_number: " 5", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Residual", album: "The Fall of Hearts", track_number: " 6", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Serac", album: "The Fall of Hearts", track_number: " 7", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Last Song Before the Fade", album: "The Fall of Hearts", track_number: " 8", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Shifts", album: "The Fall of Hearts", track_number: " 9", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "The Night Subscriber", album: "The Fall of Hearts", track_number: "10", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Pale Flag", album: "The Fall of Hearts", track_number: "11", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Passer", album: "The Fall of Hearts", track_number: "12", year: "2016", artist: katatonia, album_image: katatonia_the_fall_of_hearts_image)
Song.create!( name: "Untitled", album: "Untrue", track_number: " 1", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Archangel", album: "Untrue", track_number: " 2", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Near Dark", album: "Untrue", track_number: " 3", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Ghost Hardware", album: "Untrue", track_number: " 4", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Endorphin", album: "Untrue", track_number: " 5", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Etched Headplate", album: "Untrue", track_number: " 6", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "In McDonalds", album: "Untrue", track_number: " 7", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Untrue", album: "Untrue", track_number: " 8", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Shell of Light", album: "Untrue", track_number: " 9", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Dog Shelter", album: "Untrue", track_number: "10", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Homeless", album: "Untrue", track_number: "11", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "UK", album: "Untrue", track_number: "12", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Raver", album: "Untrue", track_number: "13", year: "2007", artist: burial, album_image: burial_untrue_image)
Song.create!( name: "Reise, Reise", album: "Reise, Reise", track_number: " 1", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Mein Teil", album: "Reise, Reise", track_number: " 2", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Dalai Lama", album: "Reise, Reise", track_number: " 3", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Keine Lust", album: "Reise, Reise", track_number: " 4", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Los", album: "Reise, Reise", track_number: " 5", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Amerika", album: "Reise, Reise", track_number: " 6", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Moskau", album: "Reise, Reise", track_number: " 7", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Morgenstern", album: "Reise, Reise", track_number: " 8", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Stein um Stein", album: "Reise, Reise", track_number: " 9", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Ohne Dich", album: "Reise, Reise", track_number: "10", year: "s", artist: rammstein, album_image: rammstein_reise_reise_image)
Song.create!( name: "Amour", album: "Reise, Reise", track_number: "11", year: "2004", artist: rammstein, album_image: rammstein_reise_reise_image)
